### ISSUE TITLE
Sugerencia: Para que la gráfica sea más representativa se debe agregar escala a los ejes

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2023-gandara-alvarez#12]
![imagen](https://github.com/UCC-LabCompu2/proyecto2023-gandara-alvarez/assets/8345007/9fb02523-9f52-42d0-bd23-6ea4d078c77c)

Además, sería recomendable desplazar el eje, para aprovechar mejor el espacio del lienzo canvas

**Comment by YagoGandara** [comment]
ya estan agregadas las escalas a los ejes
