### ISSUE TITLE
Sugerencia: Mejorar la legibilidad del readme

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2023-gandara-alvarez#5]
Para hacer el texto del readme más legible sería conveniente que emplean más variedad en el markdown:
* Ítems para el nombre de los autores
* Uso de negrita
* Link a la página de gh-pages
* En la parte de donde se explica cada página, emplear ítems ordenados y negrita.
* Emplear título de nivel 2 o 3 para la sección de tecnologías
* Emplear ítems para cada tecnología

Debería quedar algo así:
![imagen](https://github.com/UCC-LabCompu2/proyecto2023-gandara-alvarez/assets/8345007/4432d91e-e675-4b8f-90ff-f338e298cc4b)

**Comment by YagoGandara** [comment]
Yo lo ordene de otra forma profe, esta bien como lo ordene? O es preferible que sea como usted nos subio?
